# Generated by Django 5.1.6 on 2025-03-01 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_code', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('module_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.module')),
                ('professors', models.ManyToManyField(to='main.professor')),
            ],
            options={
                'unique_together': {('module', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfessorRating',
            fields=[
                ('student_prof_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('module_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.moduleinstance')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.professor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_id', 'professor_id')},
            },
        ),
    ]
