# Generated by Django 5.1.6 on 2025-03-05 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofessorrating',
            unique_together={('student_id', 'professor_id', 'module_instance_id')},
        ),
    ]
